  version: '1.29'

  services:
    mongo_db:
      image: mongo:latest
      restart: always
      volumes:
        - mongo_db:/data/db
    app1:
      build: ./app1
      ports:
        - 8887:8887

    app2:
      build: ./app2
      ports:
        - 8888:8888
      environment:
        MONGODB_URI: mongodb://mongo_db:27017
        MONGODB_NAME: mydatabase
        
  volumes:
    mongo_db: {}
