  version: '3.9'

  services:
    mongo_db:
      image: mongo:latest
      restart: always
      networks:
        - my-network
      volumes:
        - mongo_db:/data/db
    app1:
      build: ./app1
      ports:
        - 8887:8887
      networks:
        - my-network
    app2:
      build: ./app2
      ports:
        - 8888:8888
      networks:
        - my-network
      environment:
        MONGODB_URI: mongodb://mongo_db:27017
        MONGODB_NAME: mydatabase
  volumes:
    mongo_db: {}
  networks:
    my-network: